language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - nightly
  - beta
  - stable

# Add clippy
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        CLIPPY=true
      fi

# The main build
script:
  - cargo clean -p mps
  - ( ($CLIPPY && cargo test --features clippy) || cargo test)
